dist: trusty
sudo: required

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ubuntu-sdk-team/ppa
          packages:
            - gcc-5
            - g++-5
            - git
            - cppcheck
      env: COMPILER=g++-5

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then ./install_deps.sh; fi
  - git submodule update --init
  - sudo -H pip install --user cpp-coveralls
  - sudo -H python -m easy_install --upgrade pyOpenSSL

before_script:
  # use gcc-5 & g++-5
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - g++ --version
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=WjuLhR2vmRCSBHZXRVuTVrmCdo5uat7Uw

script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make cppcheck
  - time make all -j$(nproc)

after_success:
  - coveralls --include ../ --extension .cc --gcov-options '\-lp' --dump coveralls.json
